#!/usr/bin/python
# -*- encoding: utf-8 -*-

from __future__ import print_function
import sys

if len(sys.argv) < 2:
	params = ['<output file>', '<args…>']
	print('Usage: %s %s' % (sys.argv[0], ' '.join(params)))
	sys.exit(1)

outfile  = sys.argv[1]

rel_list = []
for word in sys.argv[2:]:
	rel_list.append(word)

with open(outfile, 'w') as f: print('%s' % rel_list, file=f)
