#!/usr/bin/python
# -*- encoding: utf-8 -*-

from __future__ import print_function
import sys

if len(sys.argv) < 2:
	print('Usage: %0 <map file> <months…>' % sys.argv[0],file=sys.stderr)
	sys.exit(1)

with open(sys.argv[1], 'w') as f: print(sys.argv[2:], file=f)
