#!/usr/bin/python
# -*- encoding: utf-8 -*-

from __future__ import print_function
import sys

if len(sys.argv) != 2:
	params = ['<output file>', '<target>']
	print('Usage: %s %s' % (sys.argv[0], ' '.join(params)))
	sys.exit(1)

pag_file = sys.argv[1]
target   = sys.argv[2]

with open(pag_file, 'w') as f: print('jump#Blog/%s' % target, file=f)
