#!/usr/bin/python
# -*- encoding: utf-8 -*-

from __future__ import print_function
import sys

if len(sys.argv) != 2:
	params = ['<output file>']
	print('Usage: %s %s' % (sys.argv[0], ' '.join(params)))
	sys.exit(1)

def get_old_list (filename):

	with open(filename, 'r') as f:
		return eval(f.read())

outfile  = sys.argv[1]

rel_list = []
for word in sys.stdin.readline().split():
	rel_list.append(word)

with open(outfile, 'w') as f: print('%s' % rel_list, file=f)
