#!/usr/bin/python
# -*- encoding: utf-8 -*-

from __future__ import print_function
import sys

if len(sys.argv) != 4:
	params = ['<output file>', '<source dir>', '<build dir>']
	print('Usage: %s %s' % (sys.argv[0], ' '.join(params)))
	sys.exit(1)

def get_old_list (filename):

	with open(filename, 'r') as f:
		return eval(f.read())

outfile    = sys.argv[1]
source_dir = sys.argv[2]
build_dir  = sys.argv[3]

rel_list = []
for word in sys.stdin.readline().split():
	rel_list.append(word)

print(rel_list)

