#!/usr/bin/python
# -*- encoding: utf-8 -8-

from __future__ import print_function
import sys

if len(sys.argv) < 1:
	params = []
	print('Usage: %s %s' % (sys.argv[0], ' '.join(params)))
	sys.exit(1)

print()
print()
print(sys.argv)
print()

sys.exit(1)
