#!/usr/bin/python
# -*- encoding: utf-8 -8-

from __future__ import print_function
import sys

if len(sys.argv) < 7:
	params = ['<output file>', '<list file>'
		'<years relation file>', '<blog names file>',
		'<this year>', '<months list files…>']
	print('Usage: %s %s' % (sys.argv[0], ' '.join(params)))
	sys.exit(1)

pag_file  = sys.argv[1]
list_file = sys.argv[2]
this_year = sys.argv[3]
rel_file  = sys.argv[4]
name_file = sys.argv[5]

with open(rel_file, 'r') as f:
	rel_list = eval(f.read())

try: index = rel_list.index(this_year)
except:
	print('This year (%s) is not in the list! (%s)' % (this_year, rel_list), file=sys.stderr)
	sys.exit(1)

if index > 0: prev_year = rel_list[index - 1]
else: prev_year = False

if index < len(rel_list) - 1: next_year = rel_list[index + 1]
else: next_year = False

with open(name_file, 'r') as f:
	name_map = eval(f.read())

page = []
side = []
for filename in sys.argv[6:]:
	side.append(filename.split('/')[-1].split('.')[0])
	with open(filename, 'r') as f:
		page.append(f.read().strip())

with open(pag_file, 'w') as f:

	print('title#%s' % this_year, file=f)
	print('subtitle#%s' % (name_map['13'] % this_year), file=f)

	if prev_year: print('prev#Blog/%s/#%s' % (prev_year, prev_year), file=f)
	if next_year: print('next#Blog/%s/#%s' % (next_year, next_year), file=f)

	print('start#page', file=f)
	print('br#\n'.join(page), file=f)

	print('start#side', file=f)
	for i in side:
		print('p#link##%s#%s-%s' % (name_map[i], this_year, i), file=f)

with open(list_file, 'w') as f:

	print('id#%s' % this_year, file=f)
	for i in xrange(3):
		line = []
		for j in xrange(4):
			index = 1 + i * 4 + j
			number = '%02d' % index
			name = name_map[number]
			if number in side:
				line.append('link#Blog/%s/%s/#%s' % (this_year, number, name))
			else: line.append('%s' % name)
		print('p#%s' % ('\n/\n'.join(line)), file=f)
