#!/usr/bin/python
# -*- encoding: utf-8 -*-

from __future__ import print_function
import sys

if len(sys.argv) != 2:
	print('Usage: %s %s' % (sys.argv[0], '<output file>'))
	sys.exit(1)

rel_list = []
outfile = sys.argv[1]

for word in sys.stdin.readline().split():
	rel_list.append(word)

with open(outfile, 'w') as f: print('%s' % rel_list, file=f)
