#!/usr/bin/python
# -*- encoding: utf-8 -8-

from __future__ import print_function
import sys

if len(sys.argv) < 4:
	params = ['<output file>', '<this year>', '<months list files…>']
	print('Usage: %s %s' % (sys.argv[0], ' '.join(params)))
	sys.exit(1)

outfile   = sys.argv[1]
this_year = sys.argv[2]

print()
print()
print(sys.argv)
print()

content = []

for filename in sys.argv[3:]:
	print('Reading %s' % filename)
	with open(filename, 'r') as f:
		content.append(f.read())

#with sys.stdout as f:
f = sys.stdout
if True:

	print('title#%s' % this_year, file=f)
	print('subtitle#%s' % ('News from the year %s' % this_year), file=f)
	print('prev#%s#%s', file=f)
	print('next#%s#%s', file=f)

	print('start#page', file=f)
	print('br#\n'.join(content), file=f)

print()

sys.exit(1)
