#!/usr/bin/python
# -*- enconding: utf-8 -*-

import sys

month_list = []
post_map = {}

for line in sys.stdin:
	for word in line.strip().split():

		month_list.append(word)
		print '[%s]' % word
		year, month = word.split('/')

		if year in post_map:
			post_map[year].append(month)
		else: post_map[year] = [month]

print post_map

prev = month_list[0]
for month in month_list[1:]:
	print('%s: %s' % (prev, month))
	print('%s: %s' % (month, prev))
