#!/usr/bin/python
# -*- enconding: utf-8 -*-

import sys

years = []
months = []

for word in sys.stdin.readline().split():
	years.append(word)

for word in sys.stdin.read().split():
	months.append(word)

prev_month = months[0]
prev_dep = []
for month in months[1:]:

	prev_dep.append('%s%s.post' % (sys.argv[1], month))
	print('%sBlog/%s.six: %s' % (sys.argv[3], prev_month, ' '.join(prev_dep)))

	prev_dep.pop()
	prev_dep.append('%s%s.post' % (sys.argv[1], prev_month))
	prev_month = month

print('%sBlog/%s.six: %s' % (sys.argv[3], prev_month, ' '.join(prev_dep)))
