#!/usr/bin/python
# -*- encoding: utf-8 -*-

from __future__ import print_function
import sys

import mapper
import preprocessor
import splitter
import roman

if len(sys.argv) != 8:
	args = ['<pag file>', '<pag base>', '<map file>',
		'<page location>', '<page name>',
		'<build dir>', '<touch file>']
	print("Usage: %s %s" % (sys.argv[0], ' '.join(args)), file=sys.stderr)
	sys.exit(1)

pag_file      = sys.argv[1]
pag_base      = sys.argv[2]
map_file      = sys.argv[3]
page_location = sys.argv[4]
pag_name      = sys.argv[5]
build_dir     = sys.argv[6]
touch_file    = sys.argv[7]

pp = preprocessor.Preprocessor(pag_base)
pp.parse_file(pag_file)

sp = splitter.Splitter(mapper.get(map_file, page_location))
sp.split_content(pp.content)
sp.output_tab_files(roman.convert(pag_name), build_dir)
sp.output_touch_file(touch_file, pp.origin_files)
