#!/usr/bin/python
# -*- encoding: utf-8 -*-

import sys
import re
from poster import Poster

print sys.argv

input_file  = sys.argv[1]
output_file = sys.argv[2]
rel_file    = sys.argv[3]
this_year   = sys.argv[4]
this_month  = sys.argv[5]

with open(rel_file) as f:
	rel_map = eval(f.read())
print rel_map

rel_list = []
for year,content in rel_map.items():
	for month in content:
		rel_list.append('%s/%s' % (year, month))

print rel_list

this_page = '%s/%s' % (this_year, this_month)
print this_page

index = rel_list.index(this_page)
print index

if index > 0:
	prev_rel = rel_list[index - 1]
else: prev_rel = False

if index < len(rel_list) - 1:
	next_rel = rel_list[index + 1]
else: next_rel = False

print prev_rel, next_rel

p = Poster(this_year, this_month)
p.parse_file(input_file)
p.output_post_file(output_file)

sys.exit(1)
