#!/usr/bin/python
# -*- encoding: utf-8 -*-

from __future__ import print_function
import sys

if sys.argv != 4:
	params = ['<six side file>', '<page location>', '<php file>']
	print('Usage: %s %s' % (sys.argv[0], ' '.join(params)))
	sys.exit(1)
