#!/usr/bin/python
# -*- encoding: utf-8 -*-

from __future__ import print_function
import sys

import deps

if len(sys.argv) != 3:
	args = ['.Six file', 'tab file']
	usage = 'Usage: %s <%s>' % (sys.argv[0], '> <'.join(args))
	print(usage, file=sys.stderr)
	sys.exit(1)

Six_file  = sys.argv[1]
tab_file  = sys.argv[2]

with open(tab_file, 'w') as f:
	print(deps.extract(Six_file), file=f)
