#!/usr/bin/python
# -*- encoding: utf-8 -*-

from __future__ import print_function
import sys
from converter import ContentConverter as Converter

if len(sys.argv) != 4:
	params = ['<six side file>', '<page location>', '<php file>']
	print('Usage: %s %s' % (sys.argv[0], ' '.join(params)))
	sys.exit(1)

input_file    = sys.argv[1]
page_location = sys.argv[2]
output_file   = sys.argv[3]

c = Converter('%s/LOLSIDE' % page_location)
with open(input_file, 'r') as f:
	for line in f.readlines():
		c.parse_line(line.strip())

with open(output_file, 'w') as f:
	print(c.content, file=f)
