#!/usr/bin/python
# -*- encoding: utf-8 -*-

from __future__ import print_function
import sys

if len(sys.argv) != 3:
	print('Usage: %s <input file> <output file>' % sys.argv[0])
	sys.exit(1)

def upgrade_begin (line, args):

	env = args[1]

	if env == 'inside':
		return line
	elif env == 'outside':
		return line

	else:
		print('Unknown env %s' % args)
		sys.exit(1)

def upgrade_line (line):

	print('%s' % line[:-1])

	if '#' not in line:
		return line

	token = line.strip().split('#')
	command = token[0]

	if command == 'title' or command == 'subtitle' or command == 'stitle':
		return line

	elif command == 'post':
		return line

	elif command == 'begin':
		return upgrade_begin(line, token)
	elif command == 'end':
		return '\tend#\n'

	else:
		print('Unknown command %s' % token)
		sys.exit(1)

with open(sys.argv[2], 'w') as outf:
	for line in open(sys.argv[1], 'r').readlines():
		print('%s' % upgrade_line(line), file=outf)
