#!/usr/bin/python
# -*- encoding: utf-8 -*-

from __future__ import print_function
import sys
from converter import FullConverter as Converter

if len(sys.argv) < 4:
	print ("Usage: %s <six file> <location> <php file>", file=sys.stderr)
	sys.exit(1)

input_file    = sys.argv[1]
page_location = sys.argv[2]
output_file   = sys.argv[3]

c = Converter(page_location)
c.parse_file(input_file)
c.output_page_file(output_file)
