#!/usr/bin/python
# -*- encoding: utf-8 -*-

from __future__ import print_function
import sys

if len(sys.argv) != 3:
	params = ['<six side file>', '<php file>']
	print('Usage: %s %s' % (sys.argv[0], ' '.join(params)))
	sys.exit(1)

input_file    = sys.argv[1]
output_file   = sys.argv[2]

with open(input_file, 'r') as f:
	token = f.readline().split('|')

if token[0] != 'jump':
	print('Line does not contain a jump directive! %s' % line, file=sys.stderr)
	sys.exit(1)

with open(output_file, 'w') as f:
	print('<?php header("Location: /%s");die();?>' % token[1], file=f)
