#!/usr/bin/python
# -*- encoding: utf-8 -*-

from __future__ import print_function
import sys
import getopt
#from converter import FullConverter as Converter

opts, args = getopt.gnu_getopt(sys.argv[1:], 'vdh', ['verbose', 'debug', 'help'])

for opt in opts:
	if opt == '-v' or opt == '--verbose':
		verbose = True
	elif opt == '-d' or opt == '--debug':
		debug == True
	elif opt == '-h' or opt == '--help':
		help == True

print(opts)
print(args)

#if len(sys.argv) < 4:
if len(args) != 2:
	#print ("Usage: %s <six file> <location> <php file>", file=sys.stderr)
	print ("Usage: %s <six file> <tex file>", file=sys.stderr)
	sys.exit(1)

print(sys.argv)
sys.exit(1)

c = Converter(debug, verbose)

input_file    = sys.argv[1]
page_location = sys.argv[2]
output_file   = sys.argv[3]

c = Converter(page_location)
c.parse_file(input_file)
c.output_page_file(output_file)
