#!/usr/bin/python
# -*- encoding: utf-8 -*-

from __future__ import print_function
import sys

from upgrader import Upgrader

if len(sys.argv) != 3:
	print('Usage: %s <input file> <output file>' % sys.argv[0])
	sys.exit(1)

up = Upgrader()
up.parse_file(sys.argv[1])

with open(sys.argv[2], 'w') as outf:
	print('%s' % up.content, file=outf)
