#!/usr/bin/python
# -*- encoding: utf-8 -*-

from __future__ import print_function
import sys
import getopt
#from converter import FullConverter as Converter

class Converter:

	def __init__ (self, debug, verbose):

		self.debug   = debug
		self.verbose = verbose

opts, args = getopt.gnu_getopt(sys.argv[1:], 'vdh', ['verbose', 'debug', 'help'])

verbose   = False
debug     = False
help_flag = False

for opt in opts:
	if opt == '-v' or opt == '--verbose':
		verbose = True
	elif opt == '-d' or opt == '--debug':
		debug == True
	elif opt == '-h' or opt == '--help':
		help_flag == True

def help_message (f):

	print ("Usage: %s <six file> <tex file>" % sys.argv[0],file=f)
	print (file=f)
	print (" -v --verbose : print many messages",file=f)
	print (" -d --debug   : print debug messages",file=f)
	print (" -h --help    : print this message",file=f)

if help_flag:
	help_message(sys.stdout)
	sys.exit(0)

if len(args) != 2:
	help_message(sys.stderr)
	sys.exit(1)

c = Converter(debug, verbose)
c.parse_file(args[0])
c.output_file(args[1])
sys.exit(1)
