TARGET:= WorldOfTheGods.pdf
SOURCE:= 'http://localhost/faiv/pdf/World/Of/The/Gods/World'
INPUT:= World

all:
	@rm -f $(INPUT)
	@echo $(SOURCE)
	@echo $(INPUT)
	@wget $(SOURCE)
	#@#prince $(INPUT) -o $(TARGET)
