<?php

	require_once('utils.php');

	function dump_that_year ($year, $months)
	{
		$format = '%d %04d link#Blog/%s/%s#%s';
		$slash = sprintf('%d %04d /', 0, 0);
		
		for ($i = 0; $i < 4; $i++)
		{
			$result[] = sprintf('%d %04d c#', 0, 0);

			$month = sprintf('%02d', $i * 3 + 1);
			if (array_search($month, $months) !== false)
				$result[] = sprintf($format,
					0, 0, $year, $month, name_that_month($month));
			else $result[] = sprintf('%d %04d %s', 0, 0, name_that_month($month));

			$result[] = $slash;

			$month = sprintf('%02d', $i * 3 + 2);
			if (array_search($month, $months) !== false)
				$result[] = sprintf($format,
					0, 0, $year, $month, name_that_month($month));
			else $result[] = sprintf('%d %04d %s', 0, 0, name_that_month($month));
		
			$result[] = $slash;

			$month = sprintf('%02d', $i * 3 + 3);
			if (array_search($month, $months) !== false)
				$result[] = sprintf($format,
					0, 0, $year, $month, name_that_month($month));
			else $result[] = sprintf('%d %04d %s', 0, 0, name_that_month($month));
		}

		return implode("\n", $result);
	}

	function dump_meta ($target)
	{
		$out[] = sprintf('#### %d', 1);
		$out[] = sprintf('%d %s', 0, 'AUTOGENERATED by Sixtus 0.9.8');
		$out[] = sprintf('####');

		$out[] = sprintf('%d %04d title#%s#%s',
			0, 0, 'Archivio', 'Tutte le notizie di sempre');
		$out[] = sprintf('%d %04d tab#default', 0, 0);

		file_put_contents($target, implode("\n", $out));
	}

	function dump_content ($target, $map)
	{
		$out[] = sprintf('#### %d', 0);
		$out[] = sprintf('%d %s', 0, 'AUTOGENERATED by Sixtus 0.9.8');
		$out[] = sprintf('####');

		$limit = count($map);
		$key = array_keys($map);
		
		for ($i = 0; $i < $limit; $i++)
		{
			if ($i) $out[] = sprintf('%d %04d sec#', 0, 0);
			$out[] = sprintf('%d %04d id#%s', 0, 0, $key[$i]);
			$out[] = sprintf('%d %04d title#link#Blog/%s/#%s',
				0, 0, $key[$i], $key[$i]);
			$out[] = dump_that_year ($key[$i], $map[$key[$i]]);
		}

		file_put_contents($target, implode("\n", $out));
	}

	function dump_side ($target, $map)
	{
		$out[] = sprintf('#### %d', 0);
		$out[] = sprintf('%d %s', 0, 'AUTOGENERATED by Sixtus 0.9.8');
		$out[] = sprintf('####');

		$key = array_keys($map);

		$out[] = sprintf('%d %04d title@right#Salta all&apos;anno', 0, 0);
		$out[] = sprintf('%d %04d p#', 0, 0);

		$out[] = sprintf('%d %04d tid#%s##%s', 0, 0, $key[0], $key[0]);
		array_shift($key);
		foreach ($key as $_)
			$out[] = sprintf('%d %04d tid#/ @%s@##%s', 0, 0, $_, $_);
		
		file_put_contents($target, implode("\n", $out));
	}

	# Load map
	require_once($argv[1]);

	dump_meta("$argv[2]meta.frag");
	dump_content("$argv[2]tab-default.frag", $blog_map);
	dump_side("$argv[2]side.frag", $blog_map);

	exit(0);
?>
