<?php

	require_once('utils.php');
	require_once($argv[2]);

	function dump_meta ($target, $year, $map)
	{
		list($prev, $next) = scan_for_years(array_keys($map), $year);

		$out[] = sprintf('#### %d', 1);
		$out[] = sprintf('%d %s', 0, 'AUTOGENERATED by Sixtus 0.9.8');
		$out[] = sprintf('####');

		$out[] = sprintf('%d %04d title#Notizie %s', 0, 0, $year);
		$out[] = sprintf('%d %04d short#Notizie %s', 0, 0, $year);
		$out[] = sprintf('%d %04d subtitle#Tutte le notizie %s', 0, 0, $year);

		if ($prev) $out[] = sprintf('%d %04d prev#Blog/%s/#%s',
			0, 0, $prev, $prev);
		if ($next) $out[] = sprintf('%d %04d next#Blog/%s/#%s',
			0, 0, $next, $next);

		file_put_contents(sprintf('%smeta.frag', $target), implode("\n", $out));
	}

	function dump_content ($target, $year, $months)
	{
		$out[] = sprintf('#### %d', 0);
		$out[] = sprintf('%d %s', 0, 'AUTOGENERATED by Sixtus 0.9.8');
		$out[] = sprintf('####');

		foreach ($months as $month)
		{
			$out[] = sprintf('%d %04d sec#', 0, 0);
			$out[] = sprintf('%d %04d id#%s', 0, 0, $month);
			$out[] = sprintf('%d %04d require@side#blog/%s/%s', 0, 0, $year, $month);
		}

		file_put_contents(sprintf('%stab-default.frag', $target), implode("\n", $out));
	}

	function dump_side ($target, $year, $months)
	{
		$out[] = sprintf('#### %d', 0);
		$out[] = sprintf('%d %s', 0, 'AUTOGENERATED by Sixtus 0.9.8');
		$out[] = sprintf('####');
		$out[] = sprintf('%d %04d stitle#%s', 0, 0, $year);

		foreach ($months as $month)
			$out[] = sprintf('%d %04d p#tid#%s##%s', 0, 0, name_that_month($month), $month);
	
		file_put_contents(sprintf('%sside.frag', $target), implode("\n", $out));
	}

	dump_meta($argv[3], $argv[1], $blog_map);
	dump_content($argv[3], $argv[1], $blog_map[$argv[1]]);
	dump_side($argv[3], $argv[1], $blog_map[$argv[1]]);

	exit(0);
?>
