<?php

	require_once('utils.php');

	function dump_that_year ($year, $months)
	{
		$format = '%d %04d link#Blog/%s/%s#%s';
		$slash = sprintf('%d %04d /', 0, 0);
		
		for ($i = 0; $i < 4; $i++)
		{
			$result[] = sprintf('%d %04d c#', 0, 0);

			$month = sprintf('%02d', $i * 3 + 1);
			if (array_search($month, $months) !== false)
				$result[] = sprintf($format,
					0, 0, $year, $month, name_that_month($month));
			else $result[] = sprintf('%d %04d %s', 0, 0, name_that_month($month));

			$result[] = $slash;

			$month = sprintf('%02d', $i * 3 + 2);
			if (array_search($month, $months) !== false)
				$result[] = sprintf($format,
					0, 0, $year, $month, name_that_month($month));
			else $result[] = sprintf('%d %04d %s', 0, 0, name_that_month($month));
		
			$result[] = $slash;

			$month = sprintf('%02d', $i * 3 + 3);
			if (array_search($month, $months) !== false)
				$result[] = sprintf($format,
					0, 0, $year, $month, name_that_month($month));
			else $result[] = sprintf('%d %04d %s', 0, 0, name_that_month($month));
		}

		return implode("\n", $result);
	}

	function dump_meta ($target)
	{
		$out[] = sprintf('#### %d', 1);
		$out[] = sprintf('%d %s', 0, 'AUTOGENERATED by Sixtus 0.9.8');
		$out[] = sprintf('####');

		$out[] = sprintf('%d %04d title#%s#%s',
			0, 0, 'Archivio', 'Tutte le notizie di sempre');

		file_put_contents($target, implode("\n", $out));
	}

	function dump_content ($target, $map)
	{
		$out[] = sprintf('#### %d', 0);
		$out[] = sprintf('%d %s', 0, 'AUTOGENERATED by Sixtus 0.9.8');
		$out[] = sprintf('####');

		$limit = count($map);
		$key = array_keys($map);
		
		for ($i = 0; $i < $limit; $i++)
		{
			if ($i) $out[] = sprintf('%d %04d sec#', 0, 0);
			$out[] = sprintf('%d %04d id#%s', 0, 0, $key[$i]);
			$out[] = sprintf('%d %04d title#link#Blog/%s/#%s',
				0, 0, $key[$i], $key[$i]);
			$out[] = dump_that_year ($key[$i], $map[$key[$i]]);
		}

		printf("%s\n", implode("\n", $out));
		file_put_contents($target, implode("\n", $out));
	}

	# Load map
	require_once($argv[1]);

	dump_meta("$argv[2]meta.frag");
	dump_content("$argv[2]tab-default.frag", $blog_map);

	print_r($argv);
	exit(1);

	# Load map
	require_once($argv[2]);

	$limit = count($blog_map);
	$key = array_keys($blog_map);

	$to_file[] = sprintf("title#%s#%s\n",
		'Archivio', 'Tutte le notizie di sempre');
	$to_file[] = sprintf("start#page\n");
	
	### body
	for ($i = 0; $i < $limit; $i++)
	{
		if ($i) $to_file[] = sprintf("\tsec#\n");
		$to_file[] = sprintf("\tid#%s\n", $key[$i]);
		$to_file[] = sprintf("\ttitle#link#Blog/%s/#%s\n", $key[$i], $key[$i]);
		$to_file[] = dump_that_year ($key[$i], $blog_map[$key[$i]]);
	}
	### body

	$to_file[] = sprintf("stop#page\n");
	$to_file[] = sprintf("start#side\n");

	### side
	$to_file[] = sprintf("\ttitle@right#Salta all'anno\n");
	$to_file[] = sprintf("\tp#tid#%s##%s\n", $key[0], $key[0]);
	for ($i = 1; $i < $limit; $i++)
		$to_file[] = sprintf("\t/\n\ttid#%s##%s\n", $key[$i], $key[$i]);
	### side
	
	$to_file[] = sprintf("stop#side\n");

	file_put_contents($argv[1], $to_file);
	die();

?>
