<?php

	require_once('utils.php');

	function dig_posts ($prefix, $year, $month)
	{
		$c = array();
		$target = sprintf('%s%s/%s/c.php', $prefix, $year, $month);

		if (!is_file($target)) 
		{
			printf("Cannot locate [%s]\n", $target);
			exit(1);
		}
		
		require($target);
		return $c;
	}

	function dump_meta($target)
	{
		$out[] = sprintf('#### %d', 1);
		$out[] = sprintf('%d %s', 0, 'AUTOGENERATED by Sixtus 0.9.8');
		$out[] = sprintf('####');

		$out[] = sprintf('%d %04d title#%s#%s', 0, 0, 'Novità', 'Le notizie più recenti');
		$out[] = sprintf('%d %04d next#%s#%s', 0, 0, 'Blog/ARCHIVIO/', 'Archivio');
		$out[] = sprintf('%d %04d tab#default', 0, 0);

		file_put_contents($target, implode("\n", $out));
	}

	function dump_content($target, $year, $news)
	{
		$out[] = sprintf('#### %d', 0);
		$out[] = sprintf('%d %s', 0, 'AUTOGENERATED by Sixtus 0.9.8');
		$out[] = sprintf('####');

		$i = 0;
		$m = $news[0][1];
		foreach ($news as $_)
		{
			if ($i++)
				if ($m == $_[1]) $out[] = sprintf('%d %04d sec#', 0, 0);
				else $out[] = sprintf('%d %04d sec#br', 0, 0);
			$m = $_[1];
			$out[] = sprintf('%d %04d require@tab@%s#blog/%s/%s',
				0, 0, $_[2], $_[0], $_[1]);
		}

		file_put_contents($target, implode("\n", $out));
	}

	function dump_side ($target, $year, $sides)
	{
		$out[] = sprintf('#### %d', 0);
		$out[] = sprintf('%d %s', 0, 'AUTOGENERATED by Sixtus 0.9.8');
		$out[] = sprintf('####');

		$i = 0;
		foreach (array_keys($sides) as $year)
			foreach (array_keys($sides[$year]) as $month)
			{
				$out[] = sprintf('0 0000 stitle@right#link#Blog/%s/%02d/#%s@ %s',
					$year, $month, name_that_month($month), $year);
				$pday = '00';
				foreach (array_keys($sides[$year][$month]) as $day)
				{
					$cday = sprintf('%02d', $day);
					if ($pday != $cday)
						$out[] = sprintf('0 0000 p#<code>%02d/%02d</code> –', $day, $month);
					else $out[] = sprintf('0 0000 &amp;');
					$out[] = sprintf('0 0000 link#Blog/%04d/%02d/#%s#%s',
						$year, $month, $sides[$year][$month][$day], $day);
					$pday = $cday;
				}
			}

		foreach (array_keys($sides) as $year)
			foreach (array_keys($sides[$year]) as $month)
			{
				if ($i++) $out[] = sprintf('%d %04d sec#br', 0, 0);
				$out[] = sprintf('%d %04d require@side#blog/%s/%s', 0, 0, $year, $month);
			}

		file_put_contents($target, implode("\n", $out));
	}

	# Load map
	require_once($argv[1]);

	$i = 0;
	$limit = 15;
	foreach (array_reverse(array_keys($blog_map)) as $year)
		foreach (array_reverse($blog_map[$year]) as $month)
			foreach (dig_posts($argv[2], $year, $month) as $post)
			{
				if ($i < $limit) $i++; else break 3;

				$news[] = array($year, $month, $post[0]);
				$sides[$year][$month][$post[0]] = $post[1];
			}

	dump_meta("$argv[2]meta.frag");
	dump_content("$argv[2]tab-default.frag", $year, $news);
	dump_side("$argv[2]side.frag", $year, $sides);

	exit(0);
?>
