<?php

	function dig_posts ($prefix, $year, $month)
	{
		$c = array();
		$target = sprintf('%s%s/%s/c.php', $prefix, $year, $month);

		if (!is_file($target)) 
		{
			printf("Cannot locate [%s]\n", $target);
			exit(1);
		}
		
		require($target);
		return $c;
	}

	function dump_meta($target)
	{
		$out[] = sprintf('#### %d', 1);
		$out[] = sprintf('%d %s', 0, 'AUTOGENERATED by Sixtus 0.9.8');
		$out[] = sprintf('####');

		$out[] = sprintf('%d %04d title#%s#%s', 0, 0, 'Novità', 'Le notizie più recenti');
		$out[] = sprintf('%d %04d next#%s#%s', 0, 0, 'Blog/ARCHIVIO/', 'Archivio');

		file_put_contents($target, implode("\n", $out));
	}

	function dump_content($target, $year, $news)
	{
		$out[] = sprintf('#### %d', 0);
		$out[] = sprintf('%d %s', 0, 'AUTOGENERATED by Sixtus 0.9.8');
		$out[] = sprintf('####');

		$i = 0;
		foreach ($news as $_)
		{
			if ($i++) $out[] = sprintf('%d %04d sec#br', 0, 0);
			$out[] = sprintf('%d %04d require@tab@%s#blog/%s/%s',
				0, 0, $_[2], $_[0], $_[1]);
		}

		file_put_contents($target, implode("\n", $out));
	}

	function dump_side ($target, $year, $sides)
	{
		$out[] = sprintf('#### %d', 0);
		$out[] = sprintf('%d %s', 0, 'AUTOGENERATED by Sixtus 0.9.8');
		$out[] = sprintf('####');

		$i = 0;
		foreach (array_keys($sides) as $year)
			foreach (array_keys($sides[$year]) as $month)
			{
				if ($i++) $out[] = sprintf('%d %04d sec#br', 0, 0);
				$out[] = sprintf('%d %04d require@side#blog/%s/%s', 0, 0, $year, $month);
			}

		file_put_contents($target, implode("\n", $out));
	}

	# Load map
	require_once($argv[1]);

	$i = 0;
	$limit = 15;
	foreach (array_reverse(array_keys($blog_map)) as $year)
		foreach (array_reverse($blog_map[$year]) as $month)
			foreach (dig_posts($argv[2], $year, $month) as $post)
			{
				$news[] = array($year, $month, $post);
				$sides[$year][$month] = true;

				if ($i < $limit) $i++; else break 3;
			}

	dump_meta("$argv[2]meta.frag");
	dump_content("$argv[2]tab-default.frag", $year, $news);
	dump_side("$argv[2]side.frag", $year, $sides);
	exit(0);

	$post_limit = 15;
	$counter = 0;
	foreach (array_reverse(array_keys($blog_map)) as $year)
	{
		#printf("\tNow in the year %s\n", $year);
		foreach (array_reverse($blog_map[$year]) as $month)
		{
			#printf("\t\tNow in the %s / %s\n", $month, $year);

			$source_file = sprintf('%s%s/%s.post', $argv[3], $year, $month);
			#printf("\t\tNow loading [%s]\n", $source_file);

			$source_rows = file($source_file, FILE_IGNORE_NEW_LINES);

			### Need to read whole file, than keep only the needed number posts
			$found = array();
			foreach ($source_rows as $row) if (preg_match('/^post#/', $row))
			{
				$data = split('#', $row);
				$day = $data[1];
				if (isset($found[$day])) $found[$day] += 1;
				else $found[$day] = 1;
			}

			ksort($found);
			$keys = array_reverse(array_keys($found));
		
			while ($counter < $post_limit && count($keys) > 0)
			{
				$key = $keys[0];
				$result[$counter] = array($year, $month, $key, $found[$key]);
				$sides[$year][$month] = true;
				array_shift($keys);
				$counter++;
			}
		}
	}

	#print_r($result);
	#print_r($sides);

	$to_file[] = sprintf("title#%s#%s\n", 'Novità', 'Le notizie più recenti');
	$to_file[] = sprintf("next#%s#%s\n", 'Blog/ARCHIVIO/', 'Archivio');
	
	### body
	$to_file[] = sprintf("start#page\n");
	$keys = array_keys($result);
	$limit = count($keys);
	for ($i = 0; $i < $limit; $i++)
	{
		$_ = $result[$keys[$i]];
		if ($i) $to_file[] = sprintf("\tsec#br\n");
		if ($_[3] == 1)
			$to_file[] = sprintf("\trequire@tab@%s#blog/%s/%s\n",
				$_[2], $_[0], $_[1]);
		else
			for ($j = $_[3]; $j > 0; $j--)
			{
				if ($j != $_[3]) $to_file[] = sprintf("\tsec#\n");
				$to_file[] = sprintf("\trequire@tab@%s%c#blog/%s/%s\n",
					$_[2], 96 + $j, $_[0], $_[1]);
			}
	}
	$to_file[] = sprintf("stop#page\n");
	
	### side
	$to_file[] = sprintf("start#side\n");
	$keys = array_keys($sides);
	$limit = count($keys);
	for ($i = 0; $i < $limit; $i++)
	{
		$_ = $keys[$i];
		$ljmjt = count($sides[$_]);
		for ($j = 0; $j < $ljmjt; $j++)
		{
			if ($i + $j) $to_file[] = sprintf("\tsec#br\n");
			$to_file[] = sprintf("\trequire@side#blog/%s/%s\n",
				$_, array_keys($sides[$_])[$j]);
		}
	}
	$to_file[] = sprintf("stop#side\n");

	file_put_contents($argv[1], $to_file);

?>
